# Generated by Django 5.0.6 on 2026-07-22 00:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification_preferences_and_unique_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nearby_names',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='TZ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='TZ'),
        ),
    ]
