# Generated by Django 5.0.6 on 2026-07-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('video_uploads_allowed', models.BooleanField(default=False)),
                ('max_videos_per_listing', models.PositiveSmallIntegerField(default=0)),
                ('max_video_size_mb', models.PositiveIntegerField(default=0)),
                ('max_aggregate_video_storage_mb', models.PositiveIntegerField(default=0)),
                ('allowed_video_extensions', models.CharField(default='mp4,webm', max_length=160)),
                ('allowed_video_mime_types', models.CharField(default='video/mp4,video/webm', max_length=240)),
                ('max_video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('direct_recording_allowed', models.BooleanField(default=False)),
                ('max_video_width', models.PositiveIntegerField(blank=True, null=True)),
                ('max_video_height', models.PositiveIntegerField(blank=True, null=True)),
                ('account_storage_allowance_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan'],
            },
        ),
    ]
