# Generated by Django 5.0.6 on 2026-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_videoplanentitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplanentitlement',
            name='absolute_max_video_bytes',
            field=models.PositiveBigIntegerField(default=200000000),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='maximum_recording_duration_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='maximum_video_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='optimization_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='original_retention_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='original_upload_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='recommended_standard_video_bytes',
            field=models.PositiveBigIntegerField(default=50000000),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='recommended_video_duration_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='recording_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='soft_max_video_bytes',
            field=models.PositiveBigIntegerField(default=50000000),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='total_video_storage_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoplanentitlement',
            name='upload_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
