# Generated by Django 5.0.6 on 2026-03-23 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('rental', 'Rental Property'), ('sme', 'SME / Business'), ('auto', 'Automotive')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('sold', 'Sold / Rented')], default='draft', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('location', models.CharField(max_length=120)),
                ('city', models.CharField(default='Dar es Salaam', max_length=60)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('property_type', models.CharField(blank=True, choices=[('single_room', 'Single Room'), ('self_contained', 'Self Contained'), ('bedsitter', 'Bedsitter'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedrooms'), ('3_bedroom', '3 Bedrooms'), ('4_plus', '4+ Bedrooms'), ('studio', 'Studio'), ('shared', 'Shared House'), ('hostel', 'Hostel / Student')], max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('allows_students', models.BooleanField(default=False)),
                ('amenities', models.CharField(blank=True, max_length=255)),
                ('business_category', models.CharField(blank=True, max_length=80)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('vehicle_make', models.CharField(blank=True, max_length=60)),
                ('vehicle_model', models.CharField(blank=True, max_length=60)),
                ('vehicle_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_cover', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', '-is_cover'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type', 'status'], name='listings_li_listing_1a18bd_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'status'], name='listings_li_city_3083b5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured', '-created_at'], name='listings_li_is_feat_4800c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
