# Generated by Django 5.0.6 on 2026-07-14 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingreview_listingview'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location_precision',
            field=models.CharField(choices=[('exact', 'Show exact location'), ('approximate', 'Show approximate area')], default='approximate', max_length=12),
        ),
        migrations.AddField(
            model_name='listing',
            name='nearby_landmark',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='SMEDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=10)),
                ('subcategory', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('condition', models.CharField(blank=True, max_length=30)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed price'), ('starting', 'Starting from'), ('negotiable', 'Negotiable'), ('contact', 'Contact for price')], default='fixed', max_length=20)),
                ('stock_available', models.BooleanField(default=False)),
                ('selling_unit', models.CharField(blank=True, max_length=40)),
                ('minimum_order', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('service_area', models.CharField(blank=True, max_length=160)),
                ('customers_visit', models.BooleanField(default=False)),
                ('provider_visits', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
                ('availability', models.CharField(blank=True, max_length=160)),
                ('completion_time', models.CharField(blank=True, max_length=80)),
                ('emergency_service', models.BooleanField(default=False)),
                ('materials_included', models.BooleanField(default=False)),
                ('warranty', models.BooleanField(default=False)),
                ('return_exchange', models.BooleanField(default=False)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sme_details', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('van', 'Van'), ('truck', 'Truck'), ('bus', 'Bus'), ('other', 'Other')], max_length=30)),
                ('trim', models.CharField(blank=True, max_length=60)),
                ('condition', models.CharField(choices=[('new', 'New'), ('foreign_used', 'Foreign used'), ('locally_used', 'Locally used')], max_length=20)),
                ('body_type', models.CharField(blank=True, max_length=40)),
                ('exterior_colour', models.CharField(blank=True, max_length=40)),
                ('fuel_type', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(blank=True, max_length=20)),
                ('engine_capacity_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('drivetrain', models.CharField(blank=True, max_length=20)),
                ('steering_position', models.CharField(blank=True, max_length=10)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_status', models.CharField(blank=True, max_length=30)),
                ('service_history', models.BooleanField(default=False)),
                ('accident_history', models.BooleanField(default=False)),
                ('imported', models.BooleanField(default=False)),
                ('warranty', models.BooleanField(default=False)),
                ('financing', models.BooleanField(default=False)),
                ('trade_in', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('features', models.CharField(blank=True, max_length=500)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_details', to='listings.listing')),
            ],
        ),
    ]
