# Generated by Django 5.0.6 on 2026-07-19 06:39

import django.db.models.deletion
import os
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_global_video_policy(apps, schema_editor):
    policy_model = apps.get_model('listings', 'GlobalVideoStoragePolicy')
    policy_model.objects.get_or_create(
        pk=1,
        defaults={
            'global_storage_cap_bytes': int(os.environ.get('VIDEO_GLOBAL_STORAGE_CAP_BYTES') or 8_000_000_000),
            'standard_video_bytes': int(os.environ.get('STANDARD_VIDEO_BYTES') or 50_000_000),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVideoStoragePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_storage_cap_bytes', models.PositiveBigIntegerField()),
                ('committed_bytes', models.PositiveBigIntegerField(default=0)),
                ('reserved_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploads_enabled', models.BooleanField(default=True)),
                ('recording_enabled', models.BooleanField(default=True)),
                ('optimization_enabled', models.BooleanField(default=True)),
                ('standard_video_bytes', models.PositiveBigIntegerField(default=50000000)),
                ('recommended_duration_seconds', models.PositiveIntegerField(default=60)),
                ('soft_video_size_bytes', models.PositiveBigIntegerField(default=50000000)),
                ('hard_video_size_bytes', models.PositiveBigIntegerField(default=200000000)),
                ('maximum_recording_seconds', models.PositiveIntegerField(default=120)),
                ('temporary_object_lifetime_minutes', models.PositiveIntegerField(default=60)),
                ('warning_threshold_percent', models.PositiveSmallIntegerField(default=80)),
                ('critical_threshold_percent', models.PositiveSmallIntegerField(default=95)),
                ('target_video_height', models.PositiveIntegerField(default=720)),
                ('target_frame_rate', models.PositiveIntegerField(default=30)),
                ('original_retention_enabled', models.BooleanField(default=False)),
                ('last_known_r2_usage_bytes', models.PositiveBigIntegerField(default=0)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_status', models.CharField(default='never_run', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Storage & Processing',
                'verbose_name_plural': 'Video Storage & Processing',
            },
        ),
        migrations.CreateModel(
            name='GlobalVideoStorageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('new_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('event_type', models.CharField(default='cap_changed', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='listings.globalvideostoragepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoUploadReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant', models.CharField(blank=True, max_length=120)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('declared_size', models.PositiveBigIntegerField()),
                ('expected_processed_size', models.PositiveBigIntegerField(default=0)),
                ('reserved_temporary_bytes', models.PositiveBigIntegerField(default=0)),
                ('reserved_final_bytes', models.PositiveBigIntegerField(default=0)),
                ('actual_uploaded_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actual_processed_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('uploading', 'Uploading'), ('uploaded_temporarily', 'Uploaded temporarily'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deleting', 'Deleting'), ('deleted', 'Deleted')], default='reserved', max_length=32)),
                ('expiration_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_reservations', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_reservations', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='listings.listingvideo')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='listings_vi_user_id_2c20ee_idx'), models.Index(fields=['expiration_time', 'status'], name='listings_vi_expirat_7d007e_idx')],
            },
        ),
        migrations.RunPython(seed_global_video_policy, migrations.RunPython.noop),
    ]
