# Generated by Django 5.0.6 on 2026-07-21 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_herogroup_cart_cartitem_heroimage_smeorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeorder',
            name='access_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
